version: "3.9"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rspec
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=test
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
      - db
      - mongo
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mongo
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
      MONGODB_URI: mongodb://mongo:27017/growth_api_development
      RAILS_ENV: development

volumes:
  pgdata:
  mongodata:
