default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: growth_development

test:
  <<: *default
  database: growth_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@db/growth_production" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: growth_production
  # Additional config like prepared_statements, reaping_frequency etc.
